### ISSUE TITLE
Question about fertility data in demographics.py

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-UK#10]
@jpycroft In your PR #3, the `get_fert()` function in `demographics.py` downloads fertility data for the U.K. from EuroStat. When I download the `demo_fasec` dataset as you do in your `get_fert()` function, I get the following variables of interest: `SEX`, `AGE`, and `2018`.
* I assume the values in the `2018` variable are numbers of live births.
* I assume that `SEX` is the gender fo the baby.
* I assume that `AGE` is the age of the mother.

Are these assumptions correct? Is this your understanding of the data?

**Comment by jpycroft** [comment]
@rickecon 
Rick, yes, that's right. 
The dataset is:
  "Live births by mother's age and newborn's sex [DEMO_FASEC]"
The data are given by year with 2018 being the most recent year for the UK.

Further details available from the Eurostat page:
  https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=demo_fasec&lang=en
