### ISSUE TITLE
Highly negative MTRs

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/OG-UK#33]
Getting back into debugging OG-UK after a while, I noticed that the function generating employment income MTRs for households on the FRS data produces 39 households with extremely negative MTRs. After some investigation, this is because of the childcare element of Universal Credit - all adults in the family must be in work. Increasing the earnings of every adult by £1 satisfies this formula, so households which in the baseline have a family with at least one adult unemployed and childcare costs receive hundreds of pounds in increased benefits.

I'm guessing we need to clip the MTRs to sensible ranges to avoid this polluting the rest of the tax function estimation, so I'll add that.

**Comment by nikhilwoodruff** [comment]
#35 clips the MTRs in (0, 1), so closing.

**Comment by MattHJensen** [comment]
Hi Nikhil, fwiw, it's common for us to see tax rates outside of this range in USA tax policy, especially when you begin combining central and sub-central tax and benefit systems, but also just in federal individual income taxes alone.

**Comment by MaxGhenis** [comment]
Should we be clipping MTRs? These are legitimate incentives.

**Comment by nikhilwoodruff** [comment]
Thanks- my only concern is for the cliffs, and how dependent they are on the (somewhat arbitrarily defined) step size of the MTR calculation?

**Comment by MattHJensen** [comment]
If you calculate the mtr with a penny up and a penny down, and then use the smaller (by absolute value), do the crazy ones go away? Dan Feenberg has other suggestions like that here: https://github.com/PSLmodels/Tax-Calculator/issues/2580#issuecomment-810548544
