### ISSUE TITLE
Use black for code formatting?

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-UK#4]
Since this repo is in early stages, it might be a good time to decide to use `black` or not.  Opinions?

cc @rickecon @jpycroft @nikhilwoodruff

**Comment by jpycroft** [comment]
Hi Jason, no strong view, but I'd edge towards black. Jon

cc @rickecon @jdebacker  @nikhilwoodruff

**Comment by rickecon** [comment]
Let's definitely use black for this repository. Great place to start building it in (e.g., new code base, less legacy code that might get changed).

**Comment by nikhilwoodruff** [comment]
Yep, FWIW Black has a thumbs up from me!

**Comment by jdebacker** [comment]
Resolved in PR #5
