### ISSUE TITLE
Solving the steady-state

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/OG-UK#43]
Filing this to keep track of my attempts to move the best working parametrisation of OG-UK from the default OG-Core model, to the full UK model with fitted tax functions.

Version: 0.0.1

- [x] Default OG-Core model (solves)
- [x] As above, DEP, not age-specific, start year = 2019 (solves)
- [x] As above, plus `oguk_default_parameters.json` (solves)
- [x] As above, with OpenFisca-UK linear tax function calibration
- [x] As above, with GS tax function calibration
- [ ] As above, with DEP tax function calibration (fails to solve)

@jdebacker @rickecon @jpycroft @MaxGhenis any ideas on "middle-ground" points between 3 and 4? Or I could first reforming the microsim model to make the tax functions effectively flat or otherwise simplified?

**Comment by jdebacker** [comment]
@nikhilwoodruff for a middle ground, I'd recommend fitting the linear tax rates first (before the GS or DEP functions that allow for progressive rates).

**Comment by nikhilwoodruff** [comment]
Thanks @jdebacker - updated with the success! I'll see how the TPI looks.

**Comment by nikhilwoodruff** [comment]
OK, some results and a few questions:
1. Here's what I get when just running SS functions, for the default reform which raises the basic rate of income tax from 20% to 30%. How does this compare with what we'd expect?

| Variable                       |   Baseline |    Reform |   % Change (or pp diff) |
|:-------------------------------|-----------:|----------:|------------------------:|
| GDP ($\bar{Y}$)                |  0.689195  | 0.678031  |              -1.61978   |
| Consumption ($\bar{C}$)        |  0.600977  | 0.606212  |               0.871164  |
| Capital Stock ($\bar{K}$)      |  2.3755    | 2.37737   |               0.0785319 |
| Labor ($\bar{L}$)              |  0.353969  | 0.345041  |              -2.52229   |
| Real interest rate ($\bar{r}$) |  0.0488827 | 0.0472211 |              -3.39929   |
| Wage rate ($\bar{w}$)          |  1.26558   | 1.2773    |               0.925861  |

2. The TPI takes a while to run: if there are issues, are there ways we can diagnose/test them just from SS runs?

**Comment by nikhilwoodruff** [comment]
Now runs without issue after #50.
