### ISSUE TITLE
Documentation of OpenFisca-UK describes Tax-Calculator

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/OG-UK#44]
Just noticed at [the JB documentation](https://pslmodels.github.io/OG-UK/content/calibration/tax_functions.html) - I'll update when I have a second.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  when you get around to fixing the documentation problem you mentioned in issue #44, you might also want to clarify the following documentation puzzles:

(1) In the following, there is no link to the `OG-MOD` project.  What is that?

<img width="1453" alt="Screen Shot 2022-02-10 at 10 24 43 AM" src="https://user-images.githubusercontent.com/12170745/153440649-d22199db-eb8b-45a9-96d4-75603c71ea86.png">

(2) In the following, there is no link to the DeBacker, et.al (2019) document.

<img width="1859" alt="Screen Shot 2022-02-10 at 10 26 55 AM" src="https://user-images.githubusercontent.com/12170745/153441152-e2edd513-1f3d-42bd-96fe-0f0a8f210695.png">

(3) In the following it seems to say that the OpenFisca-UK relies on IRS or CPS data.

<img width="1864" alt="Screen Shot 2022-02-10 at 10 27 20 AM" src="https://user-images.githubusercontent.com/12170745/153442022-bb74e097-64c4-4bd5-b904-c9631c2a78ec.png">

Those are US data sources, but the OpenFisca-UK documentation (below) says it uses data derived from the Family Resources Survey.

<img width="1514" alt="Screen Shot 2022-02-10 at 10 44 41 AM" src="https://user-images.githubusercontent.com/12170745/153443385-88d9e6de-7764-4b04-8ce3-ef1a89d38098.png">

**Comment by rickecon** [comment]
Thanks @nikhilwoodruff and @martinholmer for noting these problems in the `OG-UK` documentation. These issues are mostly resolved in PR #48, which will probably be merged soon.
