### ISSUE TITLE
Set up codecov

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-UK#8]
Need to:
* Put `codecov.yml` in the GitHub actions folder
* Set up webhook in Settings tab
* Set up secret in Settings tab
* Add `OG-UK-Calibration` to PSLmodels codecov.io registration

@jdebacker

**Comment by rickecon** [comment]
@jdebacker makes a strong case for waiting to add this until the repository is a little more mature.

**Comment by jdebacker** [comment]
@rickecon You can see in PR #2 that codecov reports are already being generated and shown in the conversation.  I think this solution could could well, i.e., show coverage reports in PR conversations, but don't have a codecov check as in OG-USA that gives the red X on the PR checks.  It's that red X that I wanted to avoid here as I don't like merging PRs with them, but it may be hard to start with and maintain 100% coverage of all new code as this repo hopefully adds a bunch of things quickly.

**Comment by rickecon** [comment]
@jdebacker I agree that we should add the codecov CI check later as the repo is more mature. However, we should really do it in a way that does not require 100% coverage. This is something that I am sure we can figure out. But I am happy to push this until later.

**Comment by jdebacker** [comment]
Since code coverage is now reporting, I'm closing this issue.
